global:
  #Inject config maps
  inject_maps: []

  routing:
    type:

  # global operator values
  operator:
    keycloak:
      realm:

# Name of the instance, default {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
name:
# ID of the application instance, default
appId:

# Application image
image:
  # Docker registry
  registry: "ghcr.io"
  # Docker repository (application name)
  repository: "change-me"
  # Docker image tag (application version)
  tag: "master"
  # pull policy Always | IfNotPresent | Never
  pull: IfNotPresent

# Image pull secrets
imagePullSecrets: 

# health check configuration
livenessProbe:
  url: /healthcheck

# rediness proble configuration
readinessProbe:
  url: /healthcheck

# start up probe configuration
startupProbe:
  url: /healthcheck

# pod
pod:
  port: 8080

# service
service:
  port: 8080

# Route
routing:
  # Enable or disable route
  enabled: false
  
  # Default URL
  default_url: "change.com"
  
  # path
  path:
  
  # host name
  hostName:

  # traefik | ingress
  type: none

  traefik:
    # middleware
    middleware:
      # middleware for treafik
      enabled: false
      # traefik middleware name
      name: 

  # custom service name and port for the routing
  service:
     # custom service name only for routing
    name:
     # custom service port only for routing
    port:

# Replicas
replicas: 1

# custom service account
serviceAccount:
  # enable custom service accoung
  enabled: false
  # generate custom name <app-name>.<suffix>
  suffix:  
  # fix name of the service account
  name: 

# Inject config maps
inject_maps: []

# Custom env variables as YAML structure
envCustom: 

# Kubernetes operator configuration
operator:
  # permissions
  permission:
    # enable or disable configuration for operator
    enabled: false

    spec:      
      # default deployment name (release_name-name)
      appId:
      # map of permissions
      # resource:
      #    action: description
      permissions:

  # microfrontend
  microfrontend:
    # enable or disable configuration for operator
    enabled: false

    # default remote entry path suffix
    entrySuffix: remoteEntry.js

    # definnition
    spec:
            
      description: change-me
      
      exposedModule: change-me
      
      iconName:

      note: change-me

      # list of strings
      classifications: []      

      # list of name and path
      # - name:
      #   path:
      endpoints:

      # technology is free text
      technology: ANGULAR

      # contact email
      contact: onecx@1000kit.org

      # default is app.routing.path
      remoteBaseUrl:
      
      # default is app.routing.path + entrySuffix
      remoteEntry:

      # default release name (product name)
      productName:      
      
      # default deployment name (release_name-name or appId)
      appId:

      # default deployment name (release_name-name)
      appName:

  # Keycloak operator
  keycloak:
    # enabled or disable config for operator
    enabled: false
    # keycloak realm
    realm: master
    # JSON file in string
    client:
    # JSON file in string
    roles:
    # JSON file in string
    realms:
