apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app-angular.fullname" . }}-env"
  labels:
    app: {{ template "app-angular.fullname" $ }}
{{ include "app-angular.labels.common" $ | indent 4 }}
data:
  APP_VERSION: {{ .Values.image.tag }}
  APP_ID: {{ template "app-angular.id" $ }}
  {{ if and .Values.routing.enabled .Values.routing.path }}APP_BASE_HREF: {{ .Values.routing.path }}{{ end }}