apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.fullname" . }}
{{ include "app.labels.common" $ | indent 4 }}  
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
{{ include "app.labels.common" $ | indent 8 }}
      annotations:
{{- range $map_name := .Values.inject_maps }}
        checksum/{{ $map_name | replace "-" "_" }}: {{ index $.Values.global ($map_name | replace "-" "_") }}
{{- end }}
{{- range $map_name := .Values.global.inject_maps }}
        checksum/{{ $map_name | replace "-" "_" }}: {{ index $.Values.global ($map_name | replace "-" "_") }}
{{- end }} 
    spec:
      {{- if .Values.serviceAccount.enabled }}
        {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
        {{- else if .Values.serviceAccountSuffix }} 
      serviceAccountName: {{ template "quarkus.fullname" $ }}-{{ .Values.serviceAccount.suffix }}    
        {{ else }}
      serviceAccountName: {{ template "quarkus.fullname" $ }}
        {{- end }}
      {{- end }}    
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}    
      containers:
      - name: {{ include "app.fullname" . }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull }}
        ports:
        - containerPort: {{ .Values.pod.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.url }}
            port: {{ .Values.pod.port }}
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.url }}
            port: {{ .Values.pod.port }}
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/started
            port: {{ .Values.pod.port }}
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10                            
        env:
          {{- $envVals := .Values.global.env -}}
          {{- if (.Values.env) }}
          {{- $envVals = merge .Values.env $envVals -}}
          {{- end }}
          {{- if $envVals }}
          {{- range $key,$val := $envVals }}
          - name: {{ $key }}
            value: {{ tpl ($val|toString) $ | quote }}
          {{- end }}
          {{- end }}

          {{- if .Values.env_secrets }}
          {{- range $secret_key,$secret_value := .Values.env_secrets }}
          - name: {{ $secret_key }}
            valueFrom:
              secretKeyRef:
                key:  {{ $secret_key }}
                name: {{ template "quarkus.fullname" $ }}-env
          {{- end }}        
          {{- end }}

          {{- if .Values.envCustom }} 
            {{- .Values.envCustom | toYaml | trim | nindent 10 }}
          {{- end }}

        {{- if or (.Values.global.inject_maps) (.Values.inject_maps) }}
        envFrom:
          - configMapRef:
              name: {{ template "app.fullname" $ }}-env
          {{- $im := .Values.global.inject_maps -}}
          {{- if (.Values.inject_maps) }}
          {{- $im = concat .Values.inject_maps .Values.global.inject_maps | uniq -}}
          {{- end }}
          {{- if $im }}
          {{- range $map_name := $im }}
          - configMapRef:
              name: {{ $map_name }}
          {{- end }}
          {{- end }}
        {{- end }}