{{- if .Values.routing.enabled }}
{{- if eq (include "app.routing.type" $) "traefik" }}
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: {{ template "app.fullname" $ }}
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}    
spec:
  entryPoints:
    {{- range $ep := .Values.routing.entryPoints }}
    - {{ $ep }}
    {{ end }}
    {{- range $ep := .Values.global.routing.entryPoints }}
    - {{ $ep }}
    {{ end }}
  routes:
    - kind: Rule
      match: Host(`{{ template "app.ingress.host" $ }}`){{ include "app.traefik.path" $ }}
      {{ if .Values.routing.traefik.middleware.enabled }}
      middlewares:
        - name: {{ .Values.routing.traefik.middleware.name }}
      {{ end }}
      services:
        - kind: Service
          name: {{ template "app.fullname" $ }}
          port: {{ .Values.service.port }}
{{ end }}
{{ end }}
