{{ if .Values.operator.permission.enabled }}
apiVersion: onecx.github.io/v1
kind: Permission
metadata:
  name: {{ include "app-angular.fullname" . }}
  labels:
    app: {{ include "app-angular.fullname" . }}
{{ include "app-angular.labels.common" $ | indent 4 }}    
spec:
  appId: {{ .Values.operator.permission.spec.appId | default (include "app-angular.fullname" .) }} 
  permissions: {{ if .Values.operator.permission.spec.permissions }}{{ .Values.operator.permission.spec.permissions | toYaml | nindent 4 }}{{- end }}  
{{- end }}
