{{ if .Values.operator.microservice.enabled }}
apiVersion: onecx.tkit.org/v1
kind: Microservice
metadata:
  name: {{ include "app-angular.fullname" . }}
  labels:
    app: {{ include "app-angular.fullname" . }}
{{ include "app-angular.labels.common" $ | indent 4 }}    
spec:
  productName: {{ include "app-angular.microservice.product.name" $ }}
  appId: {{ .Values.operator.microservice.spec.appId | default (include "app-angular.fullname" .) }} 
  name: {{ .Values.operator.microservice.spec.name | default (include "app-angular.fullname" .) }}
  description: {{ .Values.operator.microservice.spec.description | default (include "app-angular.fullname" .) }}
  version: {{ template "app-angular.version" $ }}
  type: {{ .Values.operator.microservice.spec.type | default .Values.name }}
{{- end }}
