kind: Service
apiVersion: v1
metadata:
  name: {{ include "app-angular.fullname" . }}
  labels:
    app: {{ include "app-angular.fullname" . }}
{{ include "app-angular.labels.common" $ | indent 4 }}
  annotations:
    description: {{ include "app-angular.fullname" . }}
spec:
  selector:
    app: {{ include "app-angular.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port }}
